### ISSUE TITLE
issue when batch_loop_size != size

### ISSUE THREAD

**Issue by alexjwilliams** [enp1s0/curand_fp16#1]
Consider the following snippet:
https://github.com/enp1s0/curand_fp16/blob/cb5337b3a16e1fbb1653e24c39af8c36cb8673c9/src/curand_fp16.cu#L79-L85
Shouldn't `curand(&curand_gen)` be `curand_uniform(&curand_gen)`? `curand()` returns an unsigned int, which (almost always) becomes `inf` after conversion to a half in line 83. Also, shouldn't `pm` be taken into account in the above code?

**Comment by enp1s0** [comment]
Thank you @alexjwilliams  for reporting the bug. I have fixed it so please pull the latest main branch and check whether the issue has been addressed. Thanks!

**Comment by alexjwilliams** [comment]
looks good to me, thanks!
